source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NKStarRatingControl_Example' do
  pod 'NKStarRatingControl', :path => '../'

  target 'NKStarRatingControl_Tests' do
    inherit! :search_paths

  end
end

