source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NKStarRatingControl_Example', :exclusive => true do
  pod 'NKStarRatingControl', :path => '../'
end

target 'NKStarRatingControl_Tests', :exclusive => true do
  pod 'NKStarRatingControl', :path => '../'

  
end
